# Generated by Django 5.1.3 on 2025-01-22 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
