# Generated by Django 5.1.3 on 2024-11-22 14:05

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_about_remove_product_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'Изображение Продукта', 'verbose_name_plural': 'Изображения Продуктов'},
        ),
        migrations.AlterField(
            model_name='about',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
