# Generated by Django 5.1.3 on 2025-01-22 06:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_remove_product_images_productimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactinquiry',
            name='interested_product',
        ),
    ]
