# Generated by Django 5.1.3 on 2024-11-22 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_productimage_options_alter_about_content'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'О нас', 'verbose_name_plural': 'О нас'},
        ),
        migrations.AlterField(
            model_name='product',
            name='contact',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
